spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_PASSWORD}

website:
  security:
    api-path: ${PERMITTED_API_PATH}
    actuator-path: ${PERMITTED_ACTUATOR_PATH}

aws:
  region: ${AWS_REGION}
  bucket:
    testimonials: ${AWS_TESTIMONIALS_PROD_BUCKET}
    projects: ${AWS_PROJECTS_PROD_BUCKET}

cors:
  allowed-origins:
    - "https://${FRONTEND_DOMAIN}"
    - "https://${FRONTEND_SUBDOMAIN}"
    - "https://${CLOUDFRONT_DOMAIN}"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - HEADERS
    - OPTIONS

logging:
  level:
    org.springframework.security: info
