spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:helix_gpo_crm_modulith}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:FB6202Borussia!}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${SECURITY_USERNAME:user}
      password: ${SECURITY_PASSWORD:password}

website:
  security:
    api-key-header: ${WEBSITE_API_KEY_HEADER:WEBSITE_API_KEY_HEADER}
    api-key: ${WEBSITE_API_KEY:api-key-value}
    api-path: ${PERMITTED_API_PATH:/api/v1/website/**}
    actuator-path: ${PERMITTED_ACTUATOR_PATH:/actuator/**}

aws:
  region: ${AWS_REGION:eu-central-1}
  access-key: ${AWS_DEV_USER_ACCESS_KEY:abc}
  secret-key: ${AWS_DEV_USER_SECRET_KEY:xyz}

cors:
  allowed-origins:
    - "http://${FRONTEND_HOST:localhost}:${FRONTEND_PORT:4200}"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - HEADERS
    - OPTIONS
